@JewelryApp.Api_HostAddress = https://localhost:7056

POST {{JewelryApp.Api_HostAddress}}/api/account/Login
Content-Type: application/json

{
  "userName": "admin",
  "password": "admin@123"
}

###

POST {{JewelryApp.Api_HostAddress}}/api/customers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImMzMzUzZDVlLWU4OTktZWUxMS04MWU0LWIwYTQ2MDgwYjZiOSIsImp0aSI6Ijg1OTIzOGM2LWMyNTAtNDljZi05NTZhLTM3NGFlZWE0Y2RhNSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAyNjYxODg2LCJpc3MiOiJodHRwczovL2pld2VscnlhcHAuaW8iLCJhdWQiOiJodHRwczovL2pld2VscnlhcHAuaW8ifQ.qNg7ImMcGmaZndlTzL_LJ720nkcv1skhNG2QolUt_PA

{
  "name": "masoud",
  "phonuNumber": "09905492104"
}

###

POST {{JewelryApp.Api_HostAddress}}/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImMzMzUzZDVlLWU4OTktZWUxMS04MWU0LWIwYTQ2MDgwYjZiOSIsImp0aSI6IjMzZjcxNGM2LTY5YjctNDQxMy05ODY1LTJjNTlhNGRlZGRlNyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAyNjU5ODIyLCJpc3MiOiJodHRwczovL2pld2VscnlhcHAuaW8iLCJhdWQiOiJodHRwczovL2pld2VscnlhcHAuaW8ifQ.AqHNa0PsGF5PHO4-7LpwJDjgNk_cj7S_e3lTK4Zmiw0
Content-Type: application/json

{
  "name": "test",
  "weight": 6.75,
  "wage": 7,
  "wageType": 1,
  "productType": 2,
  "caratType": 1,
  "categoryId": 5,
  "barcode": "234532"
}

###

GET {{JewelryApp.Api_HostAddress}}/api/productcategory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImMzMzUzZDVlLWU4OTktZWUxMS04MWU0LWIwYTQ2MDgwYjZiOSIsImp0aSI6Ijg1OTIzOGM2LWMyNTAtNDljZi05NTZhLTM3NGFlZWE0Y2RhNSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAyNjYxODg2LCJpc3MiOiJodHRwczovL2pld2VscnlhcHAuaW8iLCJhdWQiOiJodHRwczovL2pld2VscnlhcHAuaW8ifQ.qNg7ImMcGmaZndlTzL_LJ720nkcv1skhNG2QolUt_PA

###

POST {{JewelryApp.Api_HostAddress}}/api/productcategory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImMzMzUzZDVlLWU4OTktZWUxMS04MWU0LWIwYTQ2MDgwYjZiOSIsImp0aSI6Ijg1OTIzOGM2LWMyNTAtNDljZi05NTZhLTM3NGFlZWE0Y2RhNSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAyNjYxODg2LCJpc3MiOiJodHRwczovL2pld2VscnlhcHAuaW8iLCJhdWQiOiJodHRwczovL2pld2VscnlhcHAuaW8ifQ.qNg7ImMcGmaZndlTzL_LJ720nkcv1skhNG2QolUt_PA
Content-Type: application/json

{
  "name": "گربه"
}

###

PUT {{JewelryApp.Api_HostAddress}}/api/productcategory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImMzMzUzZDVlLWU4OTktZWUxMS04MWU0LWIwYTQ2MDgwYjZiOSIsImp0aSI6Ijg1OTIzOGM2LWMyNTAtNDljZi05NTZhLTM3NGFlZWE0Y2RhNSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAyNjYxODg2LCJpc3MiOiJodHRwczovL2pld2VscnlhcHAuaW8iLCJhdWQiOiJodHRwczovL2pld2VscnlhcHAuaW8ifQ.qNg7ImMcGmaZndlTzL_LJ720nkcv1skhNG2QolUt_PA
Content-Type: application/json

{
  "id": 9,
  "name": "طلا"
}

###

POST {{JewelryApp.Api_HostAddress}}/api/products
Content-Type: application/json

{
  //AddProductRequest
}

###

GET {{JewelryApp.Api_HostAddress}}/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImMzMzUzZDVlLWU4OTktZWUxMS04MWU0LWIwYTQ2MDgwYjZiOSIsImp0aSI6Ijg1OTIzOGM2LWMyNTAtNDljZi05NTZhLTM3NGFlZWE0Y2RhNSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAyNjYxODg2LCJpc3MiOiJodHRwczovL2pld2VscnlhcHAuaW8iLCJhdWQiOiJodHRwczovL2pld2VscnlhcHAuaW8ifQ.qNg7ImMcGmaZndlTzL_LJ720nkcv1skhNG2QolUt_PA

###

GET {{JewelryApp.Api_HostAddress}}/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImMzMzUzZDVlLWU4OTktZWUxMS04MWU0LWIwYTQ2MDgwYjZiOSIsImp0aSI6Ijg1OTIzOGM2LWMyNTAtNDljZi05NTZhLTM3NGFlZWE0Y2RhNSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAyNjYxODg2LCJpc3MiOiJodHRwczovL2pld2VscnlhcHAuaW8iLCJhdWQiOiJodHRwczovL2pld2VscnlhcHAuaW8ifQ.qNg7ImMcGmaZndlTzL_LJ720nkcv1skhNG2QolUt_PA

###

GET {{JewelryApp.Api_HostAddress}}/api/productcategory/Get
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImMzMzUzZDVlLWU4OTktZWUxMS04MWU0LWIwYTQ2MDgwYjZiOSIsImp0aSI6IjkzNjQzMTg5LTkxOTktNDJhMy1hYjc2LTIyNDFkYmM5Mjk3YyIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAyNzE5NzY3LCJpc3MiOiJodHRwczovL2pld2VscnlhcHAuaW8iLCJhdWQiOiJodHRwczovL2pld2VscnlhcHAuaW8ifQ.aBe4RtwhVVebDFLXHKYVQDaY-hhKfIjUvfcFDLwnhmM



###

DELETE {{JewelryApp.Api_HostAddress}}/api/productcategory

###
