@JewelryApp.Api_HostAddress = https://localhost:7056

POST {{JewelryApp.Api_HostAddress}}/api/account/Login
Content-Type: application/json

{
  "userName": "admin",
  "password": "admin@123"
}

###

POST {{JewelryApp.Api_HostAddress}}/api/customers
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImMzMzUzZDVlLWU4OTktZWUxMS04MWU0LWIwYTQ2MDgwYjZiOSIsImp0aSI6IjU3MGJmNGEwLWQyYzItNGI0ZC05ZDQxLWZhOGVkMTY0NDBiMSIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAyNDk3NTY2LCJpc3MiOiJodHRwczovL2pld2VscnlhcHAuaW8iLCJhdWQiOiJodHRwczovL2pld2VscnlhcHAuaW8ifQ.zKnWM_wB_t-4ChSeVj8ePvi8NuVARbKoG0zf9ptjAQ8

{
  "name": "masoud",
  "phonuNumber": "09905492104"
}

###

POST {{JewelryApp.Api_HostAddress}}/api/products
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImI5ZWZiNDVhLTNhOWEtZWUxMS1iNzNmLTE4YzA0ZGNjMjI5NiIsImp0aSI6IjM2NDExNTlhLTQwZWQtNDA1NS1hNzAwLWRlMDg1NmMzM2Q3MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAyNTQ4NDU2LCJpc3MiOiJodHRwczovL2pld2VscnlhcHAuaW8iLCJhdWQiOiJodHRwczovL2pld2VscnlhcHAuaW8ifQ.HynXCUkxEYOdsqG-8HZTEQ_Se4I16_bw3jXEO61ISOE
Content-Type: application/json

{
  "name": "test",
  "weight": 6.75,
  "wage": 7,
  "wageType": 1,
  "productType": 2,
  "caratType": 1,
  "categoryId": 5,
  "barcode": "234532"
}

###

GET {{JewelryApp.Api_HostAddress}}/api/productcategory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImI5ZWZiNDVhLTNhOWEtZWUxMS1iNzNmLTE4YzA0ZGNjMjI5NiIsImp0aSI6ImQ5NDgwMzRjLTg2ZTYtNDBiYi1hNzBmLTdjNGQxZmE1NTViNiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAyNTMyMjAxLCJpc3MiOiJodHRwczovL2pld2VscnlhcHAuaW8iLCJhdWQiOiJodHRwczovL2pld2VscnlhcHAuaW8ifQ._YOrXnXC-pZjkcfZmiOiTluVvVegch-lOleoRRgSRws

###

POST {{JewelryApp.Api_HostAddress}}/api/productcategory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImI5ZWZiNDVhLTNhOWEtZWUxMS1iNzNmLTE4YzA0ZGNjMjI5NiIsImp0aSI6ImQ5NDgwMzRjLTg2ZTYtNDBiYi1hNzBmLTdjNGQxZmE1NTViNiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAyNTMyMjAxLCJpc3MiOiJodHRwczovL2pld2VscnlhcHAuaW8iLCJhdWQiOiJodHRwczovL2pld2VscnlhcHAuaW8ifQ._YOrXnXC-pZjkcfZmiOiTluVvVegch-lOleoRRgSRws
Content-Type: application/json

{
  "name": "طلا"
}

###

PUT {{JewelryApp.Api_HostAddress}}/api/productcategory
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJodHRwOi8vc2NoZW1hcy54bWxzb2FwLm9yZy93cy8yMDA1LzA1L2lkZW50aXR5L2NsYWltcy9uYW1laWRlbnRpZmllciI6ImI5ZWZiNDVhLTNhOWEtZWUxMS1iNzNmLTE4YzA0ZGNjMjI5NiIsImp0aSI6IjM2NDExNTlhLTQwZWQtNDA1NS1hNzAwLWRlMDg1NmMzM2Q3MiIsImh0dHA6Ly9zY2hlbWFzLnhtbHNvYXAub3JnL3dzLzIwMDUvMDUvaWRlbnRpdHkvY2xhaW1zL25hbWUiOiJhZG1pbiIsImh0dHA6Ly9zY2hlbWFzLm1pY3Jvc29mdC5jb20vd3MvMjAwOC8wNi9pZGVudGl0eS9jbGFpbXMvcm9sZSI6IkFkbWluIiwiZXhwIjoxNzAyNTQ4NDU2LCJpc3MiOiJodHRwczovL2pld2VscnlhcHAuaW8iLCJhdWQiOiJodHRwczovL2pld2VscnlhcHAuaW8ifQ.HynXCUkxEYOdsqG-8HZTEQ_Se4I16_bw3jXEO61ISOE
Content-Type: application/json

{
  "id": 9,
  "name": "طلا"
}

###
